apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-config
  labels:
    app: qdrant
    app.kubernetes.io/name: qdrant
    app.kubernetes.io/component: vector-store
    app.kubernetes.io/part-of: cortex-plane
data:
  production.yaml: |
    service:
      max_request_size_mb: 32
      enable_tls: false
