apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: postgresql-rw-pooler
  labels:
    app.kubernetes.io/name: postgresql-rw-pooler
    app.kubernetes.io/component: database-pooler
    app.kubernetes.io/part-of: cortex-plane
spec:
  cluster:
    name: postgresql
  type: rw
  instances: 2
  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "50"
      min_pool_size: "10"
      reserve_pool_size: "10"
      server_idle_timeout: "30"
